# Jekyll config for
# https://github.com/runxel/rhino-secrets
prettyname: Rhino Secrets 🦏
theme: minima
# https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
baseurl: /rhino-secrets
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

# seo
tagline: A short overview on the secrets of Rhino 3D.
twitter:
  username: _runxel
  card: summary
social:
  name: Lucas Becker
  links:
    - https://twitter.com/_runxel
    - https://github.com/runxel
logo: /assets/img/og_img.png